# Generated by Django 5.1.4 on 2025-02-19 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DatasetTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DatasetMetadata",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("provider", models.CharField(blank=True, max_length=255)),
                ("temporal_resolution", models.CharField(blank=True, max_length=100)),
                ("spatial_resolution", models.CharField(blank=True, max_length=100)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("spatial_coverage", models.CharField(blank=True, max_length=255)),
                ("update_frequency", models.CharField(blank=True, max_length=100)),
                ("citation", models.TextField(blank=True)),
                ("license", models.CharField(blank=True, max_length=255)),
                ("terms_of_use_url", models.URLField(blank=True)),
                ("documentation_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        related_name="datasets",
                        to="geedownloader.datasettag",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="DatasetBand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("units", models.CharField(blank=True, max_length=100)),
                ("data_type", models.CharField(blank=True, max_length=50)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bands",
                        to="geedownloader.datasetmetadata",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("dataset", "name")},
            },
        ),
    ]
