# Generated by Django 5.1.4 on 2025-02-19 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("geedownloader", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetmetadata",
            name="asset_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="coordinate_system",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="data_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="doi",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="family_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="keywords",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="period",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="sample_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="scale",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="thumbnail_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="datasetmetadata",
            name="visualization_url",
            field=models.URLField(blank=True),
        ),
    ]
